import { Url } from 'node:url';

export interface ChallongeTournament {
	accept_attachments: boolean;
	allow_participant_match_reporting: boolean;
	anonymous_voting: boolean;
	category: null;
	check_in_duration: null;
	completed_at: Date | null;
	created_at: Date;
	created_by_api: boolean;
	credit_capped: boolean;
	description: string;
	game_id: number;
	group_stages_enabled: boolean;
	hide_forum: boolean;
	hide_seeds: boolean;
	hold_third_place_match: boolean;
	id: number;
	max_predictions_per_user: number;
	name: string;
	notify_users_when_matches_open: boolean;
	notify_users_when_the_tournament_ends: boolean;
	open_signup: boolean;
	participants_count: number;
	prediction_method: number;
	predictions_opened_at: Date | null;
	private: boolean;
	progress_meter: number;
	pts_for_bye: '1.0';
	pts_for_game_tie: '0.0';
	pts_for_game_win: '0.0';
	pts_for_match_tie: '0.5';
	pts_for_match_win: '1.0';
	quick_advance: boolean;
	ranked_by: 'match wins';
	require_score_agreement: boolean;
	rr_pts_for_game_tie: '0.0';
	rr_pts_for_game_win: '0.0';
	rr_pts_for_match_tie: '0.5';
	rr_pts_for_match_win: '1.0';
	sequential_pairings: boolean;
	show_rounds: boolean;
	signup_cap: null;
	start_at: Date | null;
	started_at: Date | null;
	started_checking_in_at: null;
	state: 'underway';
	swiss_rounds: number;
	teams: boolean;
	tie_breaks: ['match wins vs tied', 'game wins', 'points scored'];
	tournament_type: 'single elimination';
	updated_at: Date;
	url: string;
	description_source: string;
	subdomain: null;
	full_challonge_url: Url;
	live_image_url: Url;
	sign_up_url: null;
	review_before_finalizing: boolean;
	accepting_predictions: boolean;
	participants_locked: boolean;
	game_name: string;
	participants_swappable: boolean;
	team_convertable: boolean;
	group_stages_were_started: boolean;
	participants?: Array<{ participant: ChallongeParticipant }>;
	matches?: Array<{ match: ChallongeMatch }>;
}

export interface ChallongeParticipant {
	active: boolean;
	checked_in_at: null;
	created_at: Date;
	final_rank: null;
	group_id: null;
	icon: null;
	id: number;
	invitation_id: null;
	invite_email: null;
	misc: null;
	name: string;
	on_waiting_list: boolean;
	seed: number;
	tournament_id: number;
	updated_at: Date;
	challonge_username: null;
	challonge_email_address_verified: null;
	removable: boolean;
	participatable_or_invitation_attached: boolean;
	confirm_remove: boolean;
	invitation_pending: boolean;
	display_name_with_invitation_email_address: string;
	email_hash: null;
	username: null;
	attached_participatable_portrait_url: null;
	can_check_in: boolean;
	checked_in: boolean;
	reactivatable: boolean;
}

export interface ChallongeMatch {
	attachment_count: null;
	created_at: Date;
	group_id: null;
	has_attachment: boolean;
	id: number;
	identifier: string;
	location: null;
	loser_id: null;
	player1_id: number;
	player1_is_prereq_match_loser: boolean;
	player1_prereq_match_id: null;
	player1_votes: number | null;
	player2_id: number;
	player2_is_prereq_match_loser: boolean;
	player2_prereq_match_id: null;
	player2_votes: number | null;
	round: number;
	scheduled_time: Date | null;
	started_at: Date;
	state: 'open' | 'complete';
	tournament_id: number;
	underway_at: Date | null;
	updated_at: Date;
	winner_id: number | null;
	prerequisite_match_ids_csv: string;
	scores_csv: string;
}
